### ISSUE TITLE
Switch to Dark Sky API

### ISSUE THREAD

**Issue by kejadlen** [kejadlen/dark-sky.alfredworkflow#12]
http://status.darksky.net/2016/09/20/forecast-api-is-now-dark-sky-api.html

- [x] Change the API endpoint
- [x] Update the README
- [x] Add attribution per the [ToS](https://darksky.net/dev/docs/terms) (probably change the icon to match Dark Sky's icon and add "Powered by Dark Sky" to item 0)
- [x] Change the name of the workflow?

**Comment by drselump14** [comment]
I submitted the pull request #13
