### ISSUE TITLE
OneUpdater -> endless upgrade prompt for 2.1.0 or below

### ISSUE THREAD

**Issue by structAnkit** [kejadlen/dark-sky.alfredworkflow#20]
The latest released workflow is v2.1.0, but version.rb/info.plist on the latest master state the repo is v2.1.1. The OneUpdater version check thus asks the user to download the latest release, but as it doesn't exist the user has to manually `git clone` the repo and zip up the files and install the workflow that way.

In short, if we could have a new dark-sky.alfredworkflow created based off the latest master and released as `2.1.1` the problem will be addressed.

Going forward it would be great to have some sort of guarantee that any bumps to `version.rb` are coupled with a new release of the workflow.

**Comment by kejadlen** [comment]
Published v2.1.1. I've been meaning to make it an automatic process, but haven't gotten around to it yet.
