### ISSUE TITLE
Workflow breaks in High Sierra

### ISSUE THREAD

**Issue by allenrowand** [kejadlen/dark-sky.alfredworkflow#22]
After upgrading my laptop to 10.13, the workflow no longer returns results. Here's the debug from Alfred 3:

[2017-10-10 14:41:11][ERROR: input.scriptfilter] Code 1: /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- alphred (LoadError)
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from dark-sky.rb:4:in `<main>'

**Comment by kejadlen** [comment]
Looks like High Sierra updated Ruby from 2.3 (from Sierra's 2.0). Can you run `ruby --version` for me and let me know what the exact version is?

**Comment by allenrowand** [comment]
ruby 2.3.3p222 (2016-11-21 revision 56859) [universal.x86_64-darwin17]

**Comment by allenrowand** [comment]
ruby 2.3.3p222 (2016-11-21 revision 56859) [universal.x86_64-darwin17]

Thanks!

**Comment by kejadlen** [comment]
Can you give this a shot? https://github.com/kejadlen/dark-sky.alfredworkflow/releases/tag/v2.1.2

**Comment by allenrowand** [comment]
Sorry to be useless, but I've never installed workflows from source and don't know how to get the vendor bundle installed (it's not in the zip above). If you can point me at some instructions I'd be happy to learn.

**Comment by kejadlen** [comment]
Oops, I forgot to attach the actual workflow - it should be on the release now!

**Comment by allenrowand** [comment]
No go. I get the following error:
Starting debug for 'Dark Sky'

[2017-10-11 21:22:29][ERROR: input.scriptfilter] Code 1: /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- alphred (LoadError)
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from dark-sky.rb:4:in `<main>'

and the oddness in the screenshot:
<img width="850" alt="screen shot 2017-10-11 at 9 22 10 pm" src="https://user-images.githubusercontent.com/32688520/31479184-606ad138-aeca-11e7-8607-b812c4ca8aa8.png">

**Comment by kejadlen** [comment]
Oof. Well, I guess it was high time for me to rewrite this in Rust anyway. In the meantime, here's the simplest workaround (run these commands in the Terminal in the workflow directory):

```
sudo gem install bundler
bundle install
```

**Comment by allenrowand** [comment]
Leaving this for completeness-

1) Running bundle install returned the error "The path 
`~/Dropbox/src/github.com/kejadlen/alphred` does not exist."
2) I downloaded Alphred and put it in the above path.
3) Ran bundle install, installed XCode CLI tools as directed; re-ran 
bundle install and got:
Fetching gem metadata from https://rubygems.org/.........
Fetching version metadata from https://rubygems.org/.
Resolving dependencies...
Fetching rake 11.3.0
Installing rake 11.3.0
Fetching builder 3.2.3
Installing builder 3.2.3
Using bundler 1.15.4
Fetching coderay 1.1.1
Installing coderay 1.1.1
Fetching method_source 0.8.2
Installing method_source 0.8.2
Fetching slop 3.6.0
Installing slop 3.6.0
Using alphred 2.0.2 from source at 
`~/Dropbox/src/github.com/kejadlen/alphred`
Fetching pry 0.10.4
Installing pry 0.10.4
Bundle complete! 3 Gemfile dependencies, 8 gems now installed.
Use `bundle info [gemname]` to see where a bundled gem is installed.

Workflow still fails, debug returns the same error as before.

No need to spend time trying to get this version running. Let me know 
when the rewrite is available and I'd be happy to test for you.

**Comment by kejadlen** [comment]
Can you give this release a shot? https://github.com/kejadlen/dark-sky.alfredworkflow/releases/tag/v3.0.1

**Comment by allenrowand** [comment]
Workflow now gets the forecast, but is missing icons. Thank you for the update- this is still the best weather workflow out there!
<img width="634" alt="screen shot 2017-10-18 at 7 53 54 am" src="https://user-images.githubusercontent.com/32688520/31725615-a303d602-b3d9-11e7-840c-2dff92e5a4f3.png">

**Comment by kejadlen** [comment]
All right, how about this one? https://github.com/kejadlen/dark-sky.alfredworkflow/releases/download/v3.0.2-rc3/dark-sky.alfredworkflow

**Comment by allenrowand** [comment]
We have liftoff!
<img width="634" alt="screen shot 2017-10-18 at 8 44 40 pm" src="https://user-images.githubusercontent.com/32688520/31753412-494bf38a-b445-11e7-899b-76d357359d6d.png">
