### ISSUE TITLE
[Request] Change icons colours for better compatibility with dark themes

### ISSUE THREAD

**Issue by xilopaint** [kejadlen/dark-sky.alfredworkflow#24]
The set of icons don't work well in Alfred dark themes. Would it be possible to change their color?

**Comment by kejadlen** [comment]
Definitely possible - can you post a screenshot?

**Comment by xilopaint** [comment]
![screen shot 2017-10-28 at 12 25 51](https://user-images.githubusercontent.com/11052366/32135827-c07c3846-bbdb-11e7-910d-88c0308f2fd0.png)

**Comment by kejadlen** [comment]
Oh, you’re using the light theme. If you go to the workflow options, you should be able to enable a dark theme for the icons.

**Comment by xilopaint** [comment]
Oh, sorry! I didn't see the options.

**Comment by kejadlen** [comment]
No prob!
